const config = {
	REACT_APP_GRAPQLENDPOINT: process.env.REACT_APP_GRAPQLENDPOINT,
	REACT_APP_COINGECKO_API: process.env.REACT_APP_COINGECKO_API,
	REACT_APP_INFURA_KEY: process.env.REACT_APP_INFURA_KEY,
	REACT_APP_FORTMATIC: process.env.REACT_APP_FORTMATIC,
	REACT_APP_SERVERENDPOINT: process.env.REACT_APP_SERVERENDPOINT,
	SKIP_PREFLIGHT_CHECK: process.env.SKIP_PREFLIGHT_CHECK,
	PUBLIC_URL: process.env.PUBLIC_URL
}

export { config }